name: Build and Deploy Electron App

on:
  push:
    branches:
      - main # Trigger build on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest # You can change this to your preferred operating system

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust according to your Node.js version

      # Install dependencies (npm or pnpm)
      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            npm install -g pnpm
            pnpm install
          else
            npm install
          fi

      # Build Electron app
      - name: Build Electron App
        run: |
          npm run electron:build # Adjust if needed based on your build command

      # Upload the build artifacts using v2
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-build
          path: ./dist # Adjust based on the output folder of your Electron build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: electron-build

      # Example: Upload to S3 (adjust for your deployment platform)
      - name: Upload to S3
        run: |
          aws s3 cp ./dist s3://your-bucket-name/ --recursive # Modify for your platform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
