
name: VoiceVOX Chinese CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.15]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Run TypeScript type check
      run: pnpm vue-tsc --noEmit
    - name: Cache Electron build
      uses: actions/cache@v4
      with:
        path: |
          dist_electron
          node_modules/.cache
        key: ${{ runner.os }}-electron-build-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-electron-build-
    - name: Build Electron app
      run: pnpm electron:build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-build-${{ matrix.node-version }}
        path: dist_electron/

